# First we are gonna load the packages

```{r}
# Load necessary packages
library(rstan)
library(coda)
library(R2jags)

# set the working directory

setwd("/home/rstudio/notas2Ejemplos")
```

## primero trabajamos con jaggs

### cargamos los datos

```{r}
#--- Ejemplo 5 ---
#-Reading data-
mortality<-read.table("http://gente.itam.mx/lnieto/index_archivos/mortality.txt",header=TRUE)
n<-nrow(mortality)
plot(mortality)
plot(mortality$x,mortality$y/mortality$n)
m<-1
nef<-c(100)
xf<-c(200)

#-Defining data-
data<-list("n"=n,"ne"=mortality$n,"y"=mortality$y,"x"=mortality$x,"m"=m,"nef"=nef,"xf"=xf)
data2<-list("n"=n,"y"=mortality$y/mortality$n,"x"=mortality$x,"m"=m,"xf"=xf)

#-Defining inits-
inits<-function(){list(beta=rep(0,2),yf1=rep(1,n),yf2=1)}
inits2<-function(){list(beta=rep(0,2),phy=1,yf1=rep(1,n),yf2=1)}

#-Selecting parameters to monitor-
parsa<-c("beta","lambda","yf1","yf2")
parsbc<-c("beta","p","yf1","yf2")
parsd<-c("beta","phy","yf1","yf2")

#-Running code-
#OpenBUGS
#ej5a.sim<-bugs(data,inits,parsa,model.file="Ej5a.txt",
#              n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
#ej5b.sim<-bugs(data,inits,parsbc,model.file="Ej5b.txt",
#               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
#ej5c.sim<-bugs(data,inits,parsbc,model.file="Ej5c.txt",
#               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
#ej5d.sim<-bugs(data2,inits2,parsd,model.file="Ej5d.txt",
#               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
#JAGS
ej5a.sim<-jags(data,inits,parsa,model.file="Ej5a.txt",
              n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
ej5b.sim<-jags(data,inits,parsbc,model.file="Ej5b.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
ej5c.sim<-jags(data,inits,parasbc,model.file="Ej5c.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
ej5d.sim<-jags(data2,inits2,parsd,model.file="Ej5d.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)


```

### verificamos convergencia
```{r}
#-Monitoring chain-
ej5.sim<-ej5a.sim

#Traza de la cadena
traceplot(ej5.sim)

#Cadena

#OpenBUGS
out<-ej5.sim$sims.list

#JAGS
out<-ej5.sim$BUGSoutput$sims.list

z<-out$beta
par(mfrow=c(1,1))
plot(z)

#Multiples cadenas

#OpenBUGS
out.a<-ej5.sim$sims.array

#JAGS
out.a<-ej5.sim$BUGSoutput$sims.array

z1<-out.a[,1,1]
z2<-out.a[,2,1]
par(mfrow=c(3,2))
plot(z1,type="l",col="grey50")
lines(z2,col="firebrick2")
y1<-cumsum(z1)/(1:length(z1))
y2<-cumsum(z2)/(1:length(z2))
ymin<-min(y1,y2)
ymax<-max(y1,y2)
plot(y1,type="l",col="grey50",ylim=c(ymin,ymax))
lines(y2,col="firebrick2",ylim=c(ymin,ymax))
hist(z1,freq=FALSE,col="grey50")
hist(z2,freq=FALSE,col="firebrick2")
acf(z1)
acf(z2)

#Resumen (estimadores)
#OpenBUGS
out.sum<-ej5.sim$summary

#JAGS
out.sum<-ej5.sim$BUGSoutput$summary

#Tabla resumen
out.sum.t<-out.sum[grep("beta",rownames(out.sum)),c(1,3,7)]
out.sum.t<-cbind(out.sum.t,apply(out$beta,2,prob))
dimnames(out.sum.t)[[2]][4]<-"prob"
print(out.sum.t)

#DIC
out.dic<-ej5c.sim$DIC
out.dic<-ej5.sim$BUGSoutput$DIC
print(out.dic)


```


### analizamos

```{r}
#Predictions
out.yf<-out.sum[grep("yf1",rownames(out.sum)),]
or<-order(mortality$x)
ymin<-min(mortality$y,out.yf[,c(1,3,7)])
ymax<-max(mortality$y,out.yf[,c(1,3,7)])

par(mfrow=c(1,1))
plot(mortality$x,mortality$y,ylim=c(ymin,ymax))
#Modelo 1
lines(mortality$x[or],out.yf[or,1],lwd=2,col=2)
lines(mortality$x[or],out.yf[or,3],lty=2,col=2)
lines(mortality$x[or],out.yf[or,7],lty=2,col=2)
#Modelo 2
lines(mortality$x[or],out.yf[or,1],lwd=2,col=3)
lines(mortality$x[or],out.yf[or,3],lty=2,col=3)
lines(mortality$x[or],out.yf[or,7],lty=2,col=3)
#Modelo 3
lines(mortality$x[or],out.yf[or,1],lwd=2,col=4)
lines(mortality$x[or],out.yf[or,3],lty=2,col=4)
lines(mortality$x[or],out.yf[or,7],lty=2,col=4)
#Modelo 4
lines(mortality$x[or],out.yf[or,1],lwd=2,col=5)
lines(mortality$x[or],out.yf[or,3],lty=2,col=5)
lines(mortality$x[or],out.yf[or,7],lty=2,col=5)
#Modelo 5
lines(mortality$x[or],out.yf[or,1],lwd=2,col=6)
lines(mortality$x[or],out.yf[or,3],lty=2,col=6)
lines(mortality$x[or],out.yf[or,7],lty=2,col=6)

plot(mortality$y,out.yf[,1])
abline(a=0,b=1)
cor(mortality$y,out.yf[,1])

#Estimacion de tasas
out.tasa<-out.sum[grep("lambda",rownames(out.sum)),]
out.tasa<-out.sum[grep("p",rownames(out.sum)),]
or<-order(mortality$x)
ymin<-min(mortality$y/mortality$n,out.tasa[,c(1,3,7)])
ymax<-max(mortality$y/mortality$n,out.tasa[,c(1,3,7)])

par(mfrow=c(1,1))
plot(mortality$x,mortality$y/mortality$n,ylim=c(ymin,ymax))
#Modelo 1
lines(mortality$x[or],out.tasa[or,1],lwd=2,col=2)
lines(mortality$x[or],out.tasa[or,3],lty=2,col=2)
lines(mortality$x[or],out.tasa[or,7],lty=2,col=2)
#Modelo 2
lines(mortality$x[or],out.tasa[or,1],lwd=2,col=3)
lines(mortality$x[or],out.tasa[or,3],lty=2,col=3)
lines(mortality$x[or],out.tasa[or,7],lty=2,col=3)
#Modelo 3
lines(mortality$x[or],out.tasa[or,1],lwd=2,col=4)
lines(mortality$x[or],out.tasa[or,3],lty=2,col=4)
lines(mortality$x[or],out.tasa[or,7],lty=2,col=4)
#Modelo 4
lines(mortality$x[or],out.tasa[or,1],lwd=2,col=5)
lines(mortality$x[or],out.tasa[or,3],lty=2,col=5)
lines(mortality$x[or],out.tasa[or,7],lty=2,col=5)
#Modelo 5
lines(mortality$x[or],out.tasa[or,1],lwd=2,col=6)
lines(mortality$x[or],out.tasa[or,3],lty=2,col=6)
lines(mortality$x[or],out.tasa[or,7],lty=2,col=6)

```