# First we are gonna load the packages

```{r}
# Load necessary packages
library(rstan)
library(coda)
library(R2jags)

# set the working directory

setwd("/home/rstudio/notas2Ejemplos")
```

## primero lo haremos con jaggs

```{r}
#--- Ejemplo 3 ---
#-Reading data-
calif<-read.table("http://gente.itam.mx/lnieto/index_archivos/calificaciones.txt",header=TRUE)
n<-nrow(calif)
plot(calif$MO,calif$SP)

#-Defining data-
data<-list("n"=n,"y"=calif$SP,"x"=calif$MO)

#-Defining inits-
inits<-function(){list(beta=rep(0,2),tau=1,yf=rep(0,n))} #parte 1
inits<-function(){list(beta=rep(0,6),tau=1,yf=rep(0,n))} #parte 2

#-Selecting parameters to monitor-
parameters<-c("beta","tau","yf")

#-Running code-
#OpenBUGS
#ej3.sim<-bugs(data,inits,parameters,model.file="Ej3.txt",
#              n.iter=10000,n.chains=2,n.burnin=1000,n.thin=1)
#ej3a.sim<-bugs(data,inits,parameters,model.file="Ej3a.txt",
#              n.iter=100000,n.chains=2,n.burnin=10000,n.thin=5)
#ej3b.sim<-bugs(data,inits,parameters,model.file="Ej3b.txt",
#              n.iter=20000,n.chains=2,n.burnin=10000,n.thin=200)
#JAGS
ej3.sim<-jags(data,inits,parameters,model.file="Ej3.txt",
              n.iter=10000,n.chains=2,n.burnin=1000,n.thin=1)
ej3a.sim<-jags(data,inits,parameters,model.file="Ej3a.txt",
               n.iter=100000,n.chains=2,n.burnin=10000,n.thin=5)
ej3b.sim<-jags(data,inits,parameters,model.file="Ej3b.txt",
              n.iter=10000,n.chains=2,n.burnin=1000,n.thin=1)

```


```{r}
#-Monitoring chain-

#Traza de la cadena
traceplot(ej3b.sim)

#Cadena

#OpenBUGS
#out<-ej3.sim$sims.list
#out<-ej3b.sim$sims.list

#JAGS
out<-ej3.sim$BUGSoutput$sims.list
out<-ej3b.sim$BUGSoutput$sims.list

z<-out$beta
par(mfrow=c(1,1))
plot(z)

z<-out$beta
pairs(z)

#Multiples cadenas

#OpenBUGS
#out.a<-ej3b.sim$sims.array

#JAGS
out.a<-ej3b.sim$BUGSoutput$sims.array

z1<-out.a[,1,2]
z2<-out.a[,2,2]
par(mfrow=c(3,2))
plot(z1,type="l",col="grey50")
lines(z2,col="firebrick2")
y1<-cumsum(z1)/(1:length(z1))
y2<-cumsum(z2)/(1:length(z2))
ymin<-min(y1,y2)
ymax<-max(y1,y2)
plot(y1,type="l",col="grey50",ylim=c(ymin,ymax))
lines(y2,col="firebrick2",ylim=c(ymin,ymax))
hist(z1,freq=FALSE,col="grey50")
hist(z2,freq=FALSE,col="firebrick2")
acf(z1)
acf(z2)

#Resumen (estimadores)
#OpenBUGS
#out.sum<-ej3.sim$summary
#out.sum<-ej3b.sim$summary

#JAGS
out.sum<-ej3b.sim$BUGSoutput$summary

#Tabla resumen
out.sum.t<-out.sum[grep("beta",rownames(out.sum)),c(1,3,7)]
out.sum.t<-cbind(out.sum.t,apply(out$beta,2,prob))
dimnames(out.sum.t)[[2]][4]<-"prob"
print(out.sum.t)

#DIC
out.dic<-ej3b.sim$DIC
out.dic<-ej3.sim$BUGSoutput$DIC
print(out.dic)

#Predictions
out.yf<-out.sum[grep("yf",rownames(out.sum)),]
or<-order(calif$MO)
ymin<-min(calif$SP,out.yf[,c(1,3,7)])
ymax<-max(calif$SP,out.yf[,c(1,3,7)])
par(mfrow=c(1,1))
plot(calif$MO,calif$SP,ylim=c(ymin,ymax))
lines(calif$MO[or],out.yf[or,1],lwd=2,col=2)
lines(calif$MO[or],out.yf[or,3],lty=2,col=2)
lines(calif$MO[or],out.yf[or,7],lty=2,col=2)

plot(calif$SP,out.yf[,1])
R2<-(cor(calif$SP,out.yf[,1]))^2
print(R2)

```

## ahora lo haremos con rstan

```{r}

```