# First we are gonna load the packages

```{r}
# Load necessary packages
library(rstan)
library(coda)
library(R2jags)

# set the working directory

setwd("/home/rstudio/notas4Ejemplos")
```

## primero trabajamos con jaggs

### cargamos los datos

```{r}
#-Reading data-
desastres<-read.table("http://gente.itam.mx/lnieto/index_archivos/desastres.txt",header=TRUE)
n<-nrow(desastres)
plot(desastres,type="l")
plot(desastres[2:n,2]-desastres[1:(n-1),2],type="l")

#-Defining data-
data<-list("n"=n,"y"=desastres$No.Desastres,"x"=desastres$Anho)
data2<-list("n"=n,"y"=c(desastres$No.Desastres[1:(n-6)],rep(NA,6)),"x"=desastres$Anho)
data3<-list("n"=n,"y"=desastres$No.Desastres+0.1,"x"=desastres$Anho/1000)

#-Defining inits-
initsa1<-function(){list(beta=rep(0,2),yf1=rep(1,n))}
initsa2<-function(){list(beta=rep(0,2),aux=1,yf1=rep(1,n))}
initsa3<-function(){list(beta=rep(0,2),a=1,yf1=rep(1,n))}
initsb1<-function(){list(beta=rep(0,2),aux2=1,yf1=rep(1,n))}
initsb2<-function(){list(beta=rep(0,2),aux=1,aux2=1,yf1=rep(1,n))}
initsb3<-function(){list(beta=rep(0,2),a=1,aux2=1,yf1=rep(1,n))}
initsc<-function(){list(beta=rep(0,n),tau.b=1,yf1=rep(1,n))}
initsd<-function(){list(mu=rep(1,n),tau.b=1,yf1=rep(1,n))}

#-Selecting parameters to monitor-
parsa1<-c("beta","yf1","mu")
parsa2<-c("beta","yf1","mu","r")
parsa3<-c("beta","yf1","mu","a")
parsb1<-c("beta","yf1","mu","tau")
parsb2<-c("beta","yf1","mu","tau","r")
parsb3<-c("beta","yf1","mu","tau","a")
parscd<-c("tau.b","yf1","mu")

#-Running code-
#OpenBUGS
#ej6a1.sim<-bugs(data,initsa1,parsa1,model.file="Ej6a1.txt",
#               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6a2.sim<-bugs(data,initsa2,parsa2,model.file="Ej6a2.txt",
#                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6a3.sim<-bugs(data3,initsa3,parsa3,model.file="Ej6a3.txt",
#                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6b1.sim<-bugs(data,initsb1,parsb1,model.file="Ej6b1.txt",
#               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6b2.sim<-bugs(data,initsb2,parsb2,model.file="Ej6b2.txt",
#                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6b3.sim<-bugs(data3,initsb3,parsb3,model.file="Ej6b3.txt",
#                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6c.sim<-bugs(data,initsc,parscd,model.file="Ej6c.txt",
#               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#ej6d.sim<-bugs(data,initsd,parscd,model.file="Ej6d.txt",
#               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
#JAGS
ej6a1.sim<-jags(data,initsa1,parsa1,model.file="Ej6a1.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6a2.sim<-jags(data,initsa2,parsa2,model.file="Ej6a2.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6a3.sim<-jags(data3,initsa3,parsa3,model.file="Ej6a3.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6b1.sim<-jags(data,initsb1,parsb1,model.file="Ej6b1.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6b2.sim<-jags(data,initsb2,parsb2,model.file="Ej6b2.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6b3.sim<-jags(data3,initsb3,parsb3,model.file="Ej6b3.txt",
                n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6c.sim<-jags(data,initsc,parscd,model.file="Ej6c.txt",
               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)
ej6d.sim<-jags(data,initsd,parscd,model.file="Ej6d.txt",
               n.iter=10000,n.chains=2,n.burnin=1000,n.thin=2)

```

### verificamos convergencia

```{r}
#-Monitoring chain-
ej6.sim<-ej6a1.sim
  
#Traza de la cadena
traceplot(ej6.sim)

#Cadena

#OpenBUGS
#out<-ej6.sim$sims.list

#JAGS
out<-ej6.sim$BUGSoutput$sims.list

z<-out$beta
par(mfrow=c(1,1))
plot(z)

#Multiples cadenas

#OpenBUGS
#out.a<-ej6.sim$sims.array

#JAGS
out.a<-ej6.sim$BUGSoutput$sims.array

z1<-out.a[,1,1]
z2<-out.a[,2,1]
par(mfrow=c(3,2))
plot(z1,type="l",col="grey50")
lines(z2,col="firebrick2")
y1<-cumsum(z1)/(1:length(z1))
y2<-cumsum(z2)/(1:length(z2))
ymin<-min(y1,y2)
ymax<-max(y1,y2)
plot(y1,type="l",col="grey50",ylim=c(ymin,ymax))
lines(y2,col="firebrick2",ylim=c(ymin,ymax))
hist(z1,freq=FALSE,col="grey50")
hist(z2,freq=FALSE,col="firebrick2")
acf(z1)
acf(z2)

#Resumen (estimadores)
#OpenBUGS
out.sum<-ej6.sim$summary

#JAGS
out.sum<-ej6.sim$BUGSoutput$summary

#Tabla resumen
out.sum.t<-out.sum[grep("beta",rownames(out.sum)),c(1,3,7)]
out.sum.t<-cbind(out.sum.t,apply(out$beta,2,prob))
dimnames(out.sum.t)[[2]][4]<-"prob"
print(out.sum.t)

#DIC
out.dic<-ej6.sim$DIC
out.dic<-ej6.sim$BUGSoutput$DIC
print(out.dic)

```

### analizamos

```{r}
#Predictions
out.yf<-out.sum[grep("yf1",rownames(out.sum)),]
ymin<-min(desastres[,2],out.yf[,c(1,3,7)])
ymax<-max(desastres[,2],out.yf[,c(1,3,7)])

par(mfrow=c(1,1))
plot(desastres,type="l",col="grey80",ylim=c(ymin,ymax))
lines(desastres[,1],out.yf[,1],lwd=2,col=2)
lines(desastres[,1],out.yf[,3],lty=2,col=2)
lines(desastres[,1],out.yf[,7],lty=2,col=2)
lines(desastres[,1],out.yf[,5],lwd=2,col=4)

#Medias
out.mu<-out.sum[grep("mu",rownames(out.sum)),]
par(mfrow=c(1,1))
plot(desastres,type="l",col="grey80")
lines(desastres[,1],out.mu[,1],lwd=2,col=2)
lines(desastres[,1],out.mu[,3],lty=2,col=2)
lines(desastres[,1],out.mu[,7],lty=2,col=2)

#PONERLE MEDIANAS O ACTUALIZAR CÓDIGO

```


